// ============================================================
// domain/seed-data.js
// Datos iniciales con los que arranca la app la primera vez
// (cuando localStorage todavía está vacío). Una vez que el
// usuario empieza a operar, estos valores ya no se vuelven a
// leer — sirven solo como "fixture" de arranque.
// ============================================================

export const INITIAL_CLIENTS = [
  { id:1,  nombre:'FRIGORIFICO VISOM',                      tipo:'Frigo',          asignado:'Nacho',  estado:'Iniciado',       arranque:'2026-04-18', notas:'', notasInternas:'', particularidades:'', contactoPrincipal:{nombre:'',cargo:'',telefono:'',email:''}, contactoEncargado:{nombre:'',cargo:'',telefono:'',email:''}, historialEstados:[], tasks:[] },
  { id:2,  nombre:'FRIGORIFICO COSTANZO',                   tipo:'Frigo',          asignado:'Nacho',  estado:'Capacitacion',   arranque:'2026-06-01', notas:'', notasInternas:'', particularidades:'', contactoPrincipal:{nombre:'',cargo:'',telefono:'',email:''}, contactoEncargado:{nombre:'',cargo:'',telefono:'',email:''}, historialEstados:[], tasks:[] },
  { id:3,  nombre:'FRIGORIFICO CNEL MOLDES RIO IV',         tipo:'Frigo',          asignado:'Nacho',  estado:'',               arranque:'', notas:'', notasInternas:'', particularidades:'', contactoPrincipal:{nombre:'',cargo:'',telefono:'',email:''}, contactoEncargado:{nombre:'',cargo:'',telefono:'',email:''}, historialEstados:[], tasks:[] },
  { id:4,  nombre:'CARNES ALONSO',                          tipo:'Ciclo II',       asignado:'Nacho',  estado:'Iniciado',       arranque:'2026-04-01', notas:'', notasInternas:'', particularidades:'', contactoPrincipal:{nombre:'',cargo:'',telefono:'',email:''}, contactoEncargado:{nombre:'',cargo:'',telefono:'',email:''}, historialEstados:[], tasks:[] },
  { id:5,  nombre:'FRIGORIFICO PORKYS',                     tipo:'Ciclo II',       asignado:'Vasco',  estado:'',               arranque:'', notas:'', notasInternas:'Pendiente asignación Vasco', particularidades:'', contactoPrincipal:{nombre:'',cargo:'',telefono:'',email:''}, contactoEncargado:{nombre:'',cargo:'',telefono:'',email:''}, historialEstados:[], tasks:[] },
  { id:6,  nombre:'FRIGORIFICO PUNILLA',                    tipo:'Frigo',          asignado:'',       estado:'Iniciado',       arranque:'', notas:'', notasInternas:'Pendiente asignación Elio', particularidades:'', contactoPrincipal:{nombre:'',cargo:'',telefono:'',email:''}, contactoEncargado:{nombre:'',cargo:'',telefono:'',email:''}, historialEstados:[], tasks:[] },
  { id:7,  nombre:'AMERICAN MEAT',                          tipo:'Frigo',          asignado:'Licha',  estado:'Capacitacion',   arranque:'2026-06-01', notas:'', notasInternas:'', particularidades:'', contactoPrincipal:{nombre:'',cargo:'',telefono:'',email:''}, contactoEncargado:{nombre:'',cargo:'',telefono:'',email:''}, historialEstados:[], tasks:[] },
  { id:8,  nombre:'EXPORTMEAT - MARTIN SOCAS',              tipo:'Usuario',        asignado:'Licha',  estado:'Capacitacion',   arranque:'', notas:'', notasInternas:'', particularidades:'', contactoPrincipal:{nombre:'',cargo:'',telefono:'',email:''}, contactoEncargado:{nombre:'',cargo:'',telefono:'',email:''}, historialEstados:[], tasks:[] },
  { id:9,  nombre:'DON MIGUEL - DUILIO FARIAS',             tipo:'Carniceria',     asignado:'Vasco',  estado:'Iniciado',       arranque:'2026-04-21', notas:'', notasInternas:'', particularidades:'', contactoPrincipal:{nombre:'',cargo:'',telefono:'',email:''}, contactoEncargado:{nombre:'',cargo:'',telefono:'',email:''}, historialEstados:[], tasks:[] },
  { id:10, nombre:'CARNES TDF',                             tipo:'Frigo',          asignado:'',       estado:'Solicitar Info', arranque:'', notas:'', notasInternas:'', particularidades:'', contactoPrincipal:{nombre:'',cargo:'',telefono:'',email:''}, contactoEncargado:{nombre:'',cargo:'',telefono:'',email:''}, historialEstados:[], tasks:[] },
  { id:11, nombre:'FRIGORIFICO POKER',                      tipo:'Frigo',          asignado:'Fran',   estado:'',               arranque:'', notas:'', notasInternas:'', particularidades:'', contactoPrincipal:{nombre:'',cargo:'',telefono:'',email:''}, contactoEncargado:{nombre:'',cargo:'',telefono:'',email:''}, historialEstados:[], tasks:[] },
  { id:12, nombre:'ORIGEN PAMPA - GRUPO ALIMENTAR',         tipo:'Usuario',        asignado:'Fran',   estado:'Capacitacion',   arranque:'2026-05-04', notas:'', notasInternas:'', particularidades:'', contactoPrincipal:{nombre:'',cargo:'',telefono:'',email:''}, contactoEncargado:{nombre:'',cargo:'',telefono:'',email:''}, historialEstados:[], tasks:[] },
  { id:13, nombre:'QUETRU LEUBU - TOMAS DALVIT',           tipo:'Admin',          asignado:'Licha',  estado:'Capacitacion',   arranque:'', notas:'', notasInternas:'', particularidades:'', contactoPrincipal:{nombre:'',cargo:'',telefono:'',email:''}, contactoEncargado:{nombre:'',cargo:'',telefono:'',email:''}, historialEstados:[], tasks:[] },
  { id:14, nombre:'FRIGORIFICO TRADICION GANADERA',         tipo:'Frigo',          asignado:'Fran',   estado:'Armado de Base', arranque:'', notas:'', notasInternas:'', particularidades:'', contactoPrincipal:{nombre:'',cargo:'',telefono:'',email:''}, contactoEncargado:{nombre:'',cargo:'',telefono:'',email:''}, historialEstados:[], tasks:[] },
  { id:15, nombre:'FRIGORIFICO BENITO JUAREZ',              tipo:'Frigo',          asignado:'Elio',   estado:'Armado de Base', arranque:'2026-07-01', notas:'', notasInternas:'Confirmado con Elio', particularidades:'', contactoPrincipal:{nombre:'',cargo:'',telefono:'',email:''}, contactoEncargado:{nombre:'',cargo:'',telefono:'',email:''}, historialEstados:[], tasks:[] },
  { id:16, nombre:'FRIDECO / OSD AGROPECUARIA - ESTEBAN DEPETRIS', tipo:'Frigo + Carni', asignado:'Licha', estado:'Capacitacion', arranque:'2026-05-04', notas:'', notasInternas:'', particularidades:'', contactoPrincipal:{nombre:'',cargo:'',telefono:'',email:''}, contactoEncargado:{nombre:'',cargo:'',telefono:'',email:''}, historialEstados:[], tasks:[] },
  { id:17, nombre:'LAS PRADERAS ALMACEN DE CARNES',         tipo:'Carniceria',     asignado:'Nicky',  estado:'Iniciado',       arranque:'2026-04-01', notas:'', notasInternas:'', particularidades:'', contactoPrincipal:{nombre:'',cargo:'',telefono:'',email:''}, contactoEncargado:{nombre:'',cargo:'',telefono:'',email:''}, historialEstados:[], tasks:[] },
  { id:18, nombre:'LOS CUNADOS - CARLOS VOGT',              tipo:'Ciclo II + Carni',asignado:'Vasco', estado:'Capacitacion',   arranque:'', notas:'Arrancó 1ra Sucursal', notasInternas:'', particularidades:'', contactoPrincipal:{nombre:'',cargo:'',telefono:'',email:''}, contactoEncargado:{nombre:'',cargo:'',telefono:'',email:''}, historialEstados:[], tasks:[] },
  { id:19, nombre:'BUENOS AIRES PORK - ANDRES MOORE',       tipo:'Frigo',          asignado:'Licha',  estado:'Armado de Base', arranque:'', notas:'', notasInternas:'', particularidades:'', contactoPrincipal:{nombre:'',cargo:'',telefono:'',email:''}, contactoEncargado:{nombre:'',cargo:'',telefono:'',email:''}, historialEstados:[], tasks:[] },
  { id:20, nombre:'DON COLON / HERENCIA - RODRIGO AYALA',   tipo:'Usuario',        asignado:'',       estado:'Solicitar Info', arranque:'', notas:'', notasInternas:'', particularidades:'', contactoPrincipal:{nombre:'',cargo:'',telefono:'',email:''}, contactoEncargado:{nombre:'',cargo:'',telefono:'',email:''}, historialEstados:[], tasks:[] },
  { id:21, nombre:'GRANJA CAMILA',                          tipo:'Ciclo II + Carni',asignado:'Vasco', estado:'Solicitar Info', arranque:'', notas:'', notasInternas:'', particularidades:'', contactoPrincipal:{nombre:'',cargo:'',telefono:'',email:''}, contactoEncargado:{nombre:'',cargo:'',telefono:'',email:''}, historialEstados:[], tasks:[] },
  { id:22, nombre:'ESTANCIAS DEL SUR - PABLO DA SILVA',     tipo:'Carniceria',     asignado:'Vasco',  estado:'Capacitacion',   arranque:'', notas:'', notasInternas:'Dev Despo en el aire - confirmar', particularidades:'', contactoPrincipal:{nombre:'',cargo:'',telefono:'',email:''}, contactoEncargado:{nombre:'',cargo:'',telefono:'',email:''}, historialEstados:[], tasks:[] },
  { id:23, nombre:'RICARDO FERNANDEZ',                      tipo:'Carniceria',     asignado:'',       estado:'',               arranque:'', notas:'', notasInternas:'', particularidades:'', contactoPrincipal:{nombre:'',cargo:'',telefono:'',email:''}, contactoEncargado:{nombre:'',cargo:'',telefono:'',email:''}, historialEstados:[], tasks:[] },
  { id:24, nombre:'FRIGORIFICO METATECH - MAXIMO AGOSTI',   tipo:'Frigo',          asignado:'Vasco',  estado:'Armado de Base', arranque:'', notas:'', notasInternas:'', particularidades:'', contactoPrincipal:{nombre:'',cargo:'',telefono:'',email:''}, contactoEncargado:{nombre:'',cargo:'',telefono:'',email:''}, historialEstados:[], tasks:[] },
  { id:25, nombre:'LUCIANO QUINTANILLA',                    tipo:'Todo',           asignado:'Vasco',  estado:'',               arranque:'', notas:'', notasInternas:'Pendiente asignación Vasco', particularidades:'', contactoPrincipal:{nombre:'',cargo:'',telefono:'',email:''}, contactoEncargado:{nombre:'',cargo:'',telefono:'',email:''}, historialEstados:[], tasks:[] },
  { id:26, nombre:'CAMPO GRANDE',                           tipo:'',               asignado:'',       estado:'',               arranque:'', notas:'', notasInternas:'', particularidades:'', contactoPrincipal:{nombre:'',cargo:'',telefono:'',email:''}, contactoEncargado:{nombre:'',cargo:'',telefono:'',email:''}, historialEstados:[], tasks:[] },
  { id:27, nombre:'SALUCLA NEGOCIOS',                       tipo:'',               asignado:'',       estado:'',               arranque:'', notas:'', notasInternas:'', particularidades:'', contactoPrincipal:{nombre:'',cargo:'',telefono:'',email:''}, contactoEncargado:{nombre:'',cargo:'',telefono:'',email:''}, historialEstados:[], tasks:[] },
  { id:28, nombre:'SAN ELIAS',                              tipo:'Usuario',        asignado:'Licha',  estado:'',               arranque:'2026-06-01', notas:'', notasInternas:'', particularidades:'', contactoPrincipal:{nombre:'',cargo:'',telefono:'',email:''}, contactoEncargado:{nombre:'',cargo:'',telefono:'',email:''}, historialEstados:[], tasks:[] },
  { id:29, nombre:'BENITO JUAREZ (inst.)',                  tipo:'Frigo',          asignado:'Elio',   estado:'Instalacion',    arranque:'', notas:'', notasInternas:'', particularidades:'', contactoPrincipal:{nombre:'',cargo:'',telefono:'',email:''}, contactoEncargado:{nombre:'',cargo:'',telefono:'',email:''}, historialEstados:[], tasks:[] },
];

export const INITIAL_USERS = [
  { username: 'Gonzalo',  displayName: 'Gonzalo Quintana',    role: 'lider', password: 'gonzalo123' },
  { username: 'Nacho',    displayName: 'Ignacio Equimendia',  role: 'lider', password: 'nacho123'   },
  { username: 'Nachof',   displayName: 'Ignacio Fernandez',   role: 'lider', password: 'nachof123'  },
  { username: 'Licha',    displayName: 'Licha',               role: 'implementador', password: 'licha123', lideres: ['Nacho']   },
  { username: 'Vasco',    displayName: 'Vasco',               role: 'implementador', password: 'vasco123', lideres: ['Nacho']   },
  { username: 'Fran',     displayName: 'Fran',                role: 'implementador', password: 'fran123',  lideres: ['Gonzalo'] },
  { username: 'Elio',     displayName: 'Elio',                role: 'implementador', password: 'elio123',  lideres: ['Gonzalo'] },
  { username: 'Nicky',    displayName: 'Nicky',               role: 'implementador', password: 'nicky123', lideres: ['Nachof']  },
];

